/**
 * importMomentsSeed.js
 *
 * Reads moments_seed.json (generated by seedVideos.js) and inserts
 * the records into the `moments` table, mapped to real user IDs.
 */
require("dotenv").config();
const pool = require("./config/database");
const fs = require("fs");
const crypto = require("crypto");

const SEED_FILE = "./moments_seed.json";

async function run() {
  console.log("🚀 Starting High-Definition Moment Seeder...");

  // 1. Load JSON
  if (!fs.existsSync(SEED_FILE)) {
    console.error(`❌  ${SEED_FILE} not found. Run "node seedVideos.js" first.`);
    process.exit(1);
  }

  const seedData = JSON.parse(fs.readFileSync(SEED_FILE, "utf8"));
  console.log(`📂  Loaded ${seedData.length} HD records from ${SEED_FILE}`);

  // 2. Fetch real users
  const [users] = await pool.query("SELECT user_id FROM users LIMIT 100");
  if (users.length === 0) {
    console.error("❌  No users found. Run the main seeder first.");
    process.exit(1);
  }
  console.log(`👥  Using ${users.length} real users as creators`);

  // 3. Clear existing seeded moments for a fresh start (optional but recommended for quality reset)
  console.log("🧹 Cleaning up old moments to ensure premium quality feed...");
  try {
    await pool.query("DELETE FROM moment_hashtags");
    await pool.query("DELETE FROM moments");
    console.log("   ✅ Database cleared of old moments.");
  } catch (err) {
    console.error("   ⚠️ Could not clear table, proceeding with inserts...");
  }

  // 4. Insert moments
  let inserted = 0;
  let skipped  = 0;

  for (const item of seedData) {
    const user  = users[Math.floor(Math.random() * users.length)];
    const id    = crypto.randomUUID();

    try {
      await pool.query(
        `INSERT INTO moments
           (moment_id, user_id, caption, media_url, streaming_url, 
            thumbnail_url, media_type, category, resolution, bitrate, 
            like_count, comment_count, share_count, view_count, duration, 
            quality_score, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          id,
          user.user_id,
          item.caption,
          item.mediaUrl,
          item.streamingUrl,
          item.thumbnailUrl,
          "video",
          item.category,
          item.resolution || "1080x1920",
          item.bitrate || "6000k",
          item.likeCount || 0,
          item.commentCount || 0,
          Math.floor(Math.random() * 100), // share_count
          item.viewCount || 0,
          item.duration || 15,
          1.0, // High quality score for seeded content
          new Date(item.createdAt)
        ]
      );
      inserted++;
      
      // Auto-extract hashtags from caption
      const tags = item.caption.match(/#[a-zA-Z0-9_]+/g) || [];
      for (const tag of tags) {
        await pool.query("INSERT INTO moment_hashtags (moment_id, hashtag) VALUES (?, ?)", [id, tag.toLowerCase()]);
      }

      if (inserted % 20 === 0) {
        process.stdout.write(`   ⏳  Provisioned ${inserted}/${seedData.length} premium moments...\r`);
      }
    } catch (err) {
      console.error(`\n   ⚠️  Skipped: ${err.message.slice(0, 100)}`);
      skipped++;
    }
  }

  console.log(`\n✨  Seeding Complete!`);
  console.log(`✅  Total Premium HD Moments: ${inserted}`);
  console.log(`⚠️  Skipped: ${skipped}`);
  process.exit(0);
}

run().catch(err => {
  console.error("❌  Fatal Error during seeding:", err);
  process.exit(1);
});
