/**
 * importMomentsSeed.js
 *
 * Reads moments_seed.json (generated by seedVideos.js) and inserts
 * the records into the `moments` table, mapped to real user IDs.
 *
 * Usage:
 *   node importMomentsSeed.js
 */
require("dotenv").config();
const pool = require("./config/database");
const fs = require("fs");
const crypto = require("crypto");

const SEED_FILE = "./moments_seed.json";

async function run() {
  // 1. Load JSON
  if (!fs.existsSync(SEED_FILE)) {
    console.error(`❌  ${SEED_FILE} not found. Run "node seedVideos.js" first.`);
    process.exit(1);
  }

  const seedData = JSON.parse(fs.readFileSync(SEED_FILE, "utf8"));
  console.log(`📂  Loaded ${seedData.length} records from ${SEED_FILE}`);

  // 2. Fetch real users
  const [users] = await pool.query("SELECT user_id FROM users LIMIT 50");
  if (users.length === 0) {
    console.error("❌  No users found. Run the main seeder first.");
    process.exit(1);
  }
  console.log(`👥  Using ${users.length} real users`);

  // 3. Ensure required columns exist (idempotent)
  const momentsCols = [
    { name: "media_url",        def: "VARCHAR(500) DEFAULT NULL" },
    { name: "media_type",       def: "VARCHAR(50) DEFAULT 'video'" },
    { name: "like_count",       def: "INT DEFAULT 0" },
    { name: "comment_count",    def: "INT DEFAULT 0" },
    { name: "share_count",      def: "INT DEFAULT 0" },
    { name: "view_count",       def: "INT DEFAULT 0" },
    { name: "category",         def: "VARCHAR(50) DEFAULT NULL" },
    { name: "completion_rate",  def: "DECIMAL(5,4) DEFAULT 1.0000" },
    { name: "quality_score",    def: "DECIMAL(5,4) DEFAULT 1.0000" }
  ];

  for (const col of momentsCols) {
    try {
      await pool.query(`ALTER TABLE moments ADD COLUMN ${col.name} ${col.def}`);
      console.log(`   ✅  Added column: moments.${col.name}`);
    } catch (e) { /* already exists — fine */ }
  }

  // 4. Insert moments
  let inserted = 0;
  let skipped  = 0;

  for (const item of seedData) {
    const user  = users[Math.floor(Math.random() * users.length)];
    const id    = crypto.randomUUID();

    try {
      await pool.query(
        `INSERT INTO moments
           (moment_id, user_id, caption, media_url, media_type,
            category, like_count, comment_count, share_count,
            view_count, duration, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          id,
          user.user_id,
          item.caption         || "",
          item.mediaUrl        || "",
          item.mediaType       || "video",
          item.category        || "general",
          item.likes           || 0,
          item.comments        || 0,
          0,                       // share_count
          item.views           || 0,
          item.duration        || 0,
          new Date(item.createdAt)
        ]
      );
      inserted++;
      if (inserted % 20 === 0) {
        process.stdout.write(`   ⏳  Inserted ${inserted}/${seedData.length}...\r`);
      }
    } catch (err) {
      console.error(`\n   ⚠️  Skipped (${err.code}): ${err.message.slice(0, 80)}`);
      skipped++;
    }
  }

  console.log(`\n✅  Done! Inserted: ${inserted}, Skipped: ${skipped}`);
  process.exit(0);
}

run().catch(err => {
  console.error("❌  Fatal:", err.message);
  process.exit(1);
});
